name: Docker Publish

on:
  release:
    types:
      - published

env:
  USERNAME: akafeng
  REPOSITORY: smartdns
  PACKAGE_REGISTRY: ghcr.io

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.PACKAGE_REGISTRY }} -u ${{ env.USERNAME }} --password-stdin
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ env.USERNAME }} --password-stdin

      - name: Docker Build
        env:
          STAGE_CACHE: ${{ env.PACKAGE_REGISTRY }}/${{ env.USERNAME }}/${{ env.REPOSITORY }}:stage
          VERSION_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ github.event.release.tag_name }}
          LATEST_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:latest
        run: |
          docker pull ${{ env.STAGE_CACHE }} || true
          docker build \
            --cache-from=${{ env.STAGE_CACHE }} \
            --tag=${{ env.VERSION_TAG }} \
            --tag=${{ env.LATEST_TAG }} \
            .

      - name: Docker Publish
        run: docker push --all-tags ${{ env.USERNAME }}/${{ env.REPOSITORY }}
